name: My NPM Package workflow
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    # 0. Checkout the code from the repository
    # 1. Install deps of our react application
    # 2. Execute automated tests
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Printing Folders
        run: ls

